version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
  postmanagement:
    image: githubguramkankava/postmanagement:latest
    container_name: postmanagement
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/postmanagement